### ISSUE TITLE
issues with host_init.sh and bind_mount.sh

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#103]
I start this ticket to keep adding issues to it:

1. Error message [here](https://44.222.241.133/#/log?jobId=3b9ml1g8r3wawwbr7jf8m&logName=stderr.autosave). `ln: failed to create symbolic link '/home/ubuntu/.local/.local': File exists` which seems an obvious bug
2. As discussed, lets remoe the redundent contents in `bind_mount.sh` that are already in entrypoint.sh

**Comment by Ashley-Tung** [comment]
In regards to issue 2, I remember why I put the entrypoint in the job script in the first place: It is because if we run with a job script, we do not run with the entrypoint script somehow
If we want to run the entrypoint directly, we would need its location in the container and run it directly, like we did with mm_jobman: https://github.com/rfeng2023/mmcloud/blob/main/src/mm_jobman.sh#L525
