### ISSUE TITLE
Add an oem_mode for mm_jobman

### ISSUE THREAD

**Issue by danielnachun** [rfeng2023/mmcloud#116]
After the successful deployment of our `pixi`/`micromamba`-based interactive sessions, we'd like to now create a similar system for batch jobs, where we use our ability to mount EFS volumes with pre-installed software instead of loading a larger container, or installing the software from scratch for every job.

The way we are envisioning this is that we will have an "OEM" EFS volume containing `pixi` and `micromamba` folders that will be mounted read-only as `$HOME/.pixi` and `$HOME/micromamba`.  These read-only `.pixi` and `micromamba` folders will contain all of the software we use throughout xQTL in a static state, where batch jobs will not be able to modify the software at all.  In some sense we can think of this a replacement for our attempts at an `xqtl_full` container with all the software we use preinstalled.  

This approach has several key advantages over what we've done before:
- No need to build different containers for different batch jobs - all the software we need is available, and we don't have to deal with long wait times for a container image to decompress
- Very low startup times for individual jobs - in this mode all we're doing is mounting some folders and then starting the job
- Jobs don't need a large EBS volume - all the jobs will be mounted to the same EFS volume for their software and we already supposed to read and write our data to an S3 bucket, so the EBS volume only needs to be large enough to fit our fairly small `tmate-minimal` container and maybe a bit of scratch space for temp files

We'll also need a `--oem-admin` mode for `mm_interactive` that will allow us to mount this "OEM" EFS volume in read-write mode to make changes or updates to this volume.  This mode will need to be used with care, as changes made here will affect all batch jobs.  For now we'll have to simply say that users need to ask permission before using this.  Eventually we may want a way to restrict this only to certain users.  Importantly, `--oem-admin` will only be available for interactive modes.  We do not want to provide any way for batch jobs submitted with `mm_jobman` to make changes to this "OEM" EFS volume.

Initially I will populate this volume with all the software we use, and once we've tested it, other users can start adding software as needed.

Please let me know what questions and clarifications are needed!

**Comment by gaow** [comment]
Proposed interface that may work for both `mm_jobman.sh` and `mm_interactive.sh`, and to also address #117.

Currently there is `--mount-packages` in `mm_interactive.sh` with boolean value. What we may do is:

1. Change `--mount-packages` behavior in `mm_interactive.sh` as `--mount-packages /mnt/efs/$FLOAT_USER:/home/ubuntu /mnt/efs/shared:/opt` by default. The `/mnt/efs/$FLOAT_USER:/home/ubuntu` is the current behavior for `--mount-packages` set to `true`.  We additionally support `/mnt/efs/shared:/opt` so we will eg make `ln` from `/mnt/efs/shared/.pixi` to `/opt/.pixi`, and similarly for micromamba. When we make our start script to additionally consider software under `/opt/.pixi` we will be able to support #117. 
2. Suppose that we have OEM packages configured under `/mnt/efs/admin` then interactive session users can have a lazy / default OEM package setup via setting `--mount-packages /mnt/efs/admin:/home/ubuntu /mnt/efs/shared:/opt`. By doing so, because all packages under `/mnt/efs/admin` and `mnt/efs/shared` are `rw` to `admin` and `ro` to regular users, when users load packages this way they will be able to use everything available but cannot install anything to them. 
3. To use packages from the container VM not mounting anything, we can add a `--no-mount-packages` switch to override `--mount-packages` regardless of the setting of `--mount-packages`
4. We can add `--mount-packages` similarly to `mm_jobman.sh` and also make default to `--mount-packages /mnt/efs/$FLOAT_USER:/home/ubuntu /mnt/efs/shared:/opt`. Then by default, users will run batch jobs with their own software setup rather than from the image. By using `--mount-packages /mnt/efs/admin:/home/ubuntu /mnt/efs/shared:/opt` the batch jobs will be using the OEM packages we install. Of course  `--no-mount-packages` will be supported if users run images such as the current `xqtl-full` docker image where all software are available. This will impelment #116
5. For `admin`, if  they set `--mount-packages /mnt/efs/admin:/home/ubuntu /mnt/efs/shared:/opt` in an interactive session, since PIXI_HOME is already set to `/home/ubuntu/.pixi` and they have `rw` to `/mnt/efs/admin` they can make changes to this to maintain the OEM packages designed for batch jobs #116
6. For `admin` if they set `--mount-packages /mnt/efs/shared:/home/ubuntu` they will be able to now  make changes to `/shared` to maintain the shared packages designed for interactive analysis   #117 .

**Comment by gaow** [comment]
@Ashley-Tung the above is summary of discussion between @gaow and @danielnachun on slack.

**Comment by danielnachun** [comment]
After reading over the code here more carefully, I think the changes needed for `mm_jobman.sh` to work here actually much simpler than I originally thought.  In our current heredoc for generating the job script we currently have this at the beginning:
```
# Function definition for calculate_max_parallel_jobs
${calculate_max_parallel_jobs_def}

# Activate environment with entrypoint in job script
${entrypoint}
```
I think all we need to do is change this to something like the following:
```
# Link folders for pixi and micromamba
username=$(whoami)
ln -sf /mnt/efs/oem/.pixi /home/${username}/.pixi
ln -sf /mnt/efs/oem/.pixi /home/${username}/micromamba
ln -sf /mnt/efs/oem/.pixi /home/${username}/.bashrc
export PATH="/home/${username}/.pixi/bin:${PATH}"

# Function definition for calculate_max_parallel_jobs
${calculate_max_parallel_jobs_def}
```
We'll also need to tweak host_init.sh (or just make a different script) so that it mounts the OEM volume instead of the one we are using for everything else.

We'll still have a bit work to set up the mounts for the interface proposed above for interactive jobs, where we'll need different symlinks depending on the "mode".  But for batch jobs I think we can just hard-code the symlinks because they are supposed to fixed.

**Comment by gaow** [comment]
@danielnachun good thinking. I forgot this embedded script. This will potentially allow `mm_jobman` to remain a standalone script unlike `mm_interactive` which has to depend on other two scripts.

**Comment by Ashley-Tung** [comment]
Some feedback and questions regarding the 6 points Gao brought up:
1. Makes sense to me!
2. I think I am a little confused here. I thought the "oem" packages are in a separate EFS than the interactive job packages. All packages for batch jobs are "shared," since there is no need to implement custom packages for each user in batch jobs. There is also no "shared" separate dir, because all packages are shared in the batch jobs anyway. This sentiment is shared in my feedback on #4.
4. Makes sense to me, but to use packages from the container, if it is a large one, we would need to increase `--rootVolSIze`
5. If you take a look at the original image setup, users will not have their own individual folders with the batch setup, which is related to the "OEM" setp, hence my confusion. Since batch setup will not need custom packages, there is no need to install packages under a `$FLOAT_USER` directory.
![image](https://github.com/user-attachments/assets/d3f660a5-7c15-4c02-ae32-4668bb2fb397)
6. Makes sense to me for interactive jobs
7. If admin did not specify `/mnt/efs/shared:/opt`, there is no `/shared` directory currently, but there is `/mnt/efs/shared`, as the EFS is mounted and the dir with the shared packages exist there.

Overall, to help me better understand, I think the two EFSs and their packages should be clearly differentiated. I thought "OEM" mode only referred to the batch/jobman submissions

I tried consolidating the conversation into this image to help us better discuss:
![image](https://github.com/user-attachments/assets/302277f4-f92c-4f26-9eac-f0253d43b04b)

**Comment by danielnachun** [comment]
> Some feedback and questions regarding the 6 points Gao brought up:
> 
> 1. Makes sense to me!
> 2. I think I am a little confused here. I thought the "oem" packages are in a separate EFS than the interactive job packages. All packages for batch jobs are "shared," since there is no need to implement custom packages for each user in batch jobs. There is also no "shared" separate dir, because all packages are shared in the batch jobs anyway. This sentiment is shared in my feedback on [Updated with parallelization functionality #4](https://github.com/rfeng2023/mmcloud/pull/4).

This summary is correct - my PR implements it this way as always linking `/mnt/efs/oem` to `/home`.  There is no batch "--oem-admin" mode as batch jobs will not be allowed to modify any software.

> 3. Makes sense to me, but to use packages from the container, if it is a large one, we would need to increase `--rootVolSIze`
We probably won't be using container packages any more, but you are correct that if the user needed to use a large image, they'd have to request a larger EBS allocation.
> 4. If you take a look at the original image setup, users will not have their own individual folders with the batch setup, which is related to the "OEM" setp, hence my confusion. Since batch setup will not need custom packages, there is no need to install packages under a `$FLOAT_USER` directory.
>    ![image](https://private-user-images.githubusercontent.com/52087355/378556745-d3f660a5-7c15-4c02-ae32-4668bb2fb397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTI2NjIsIm5iZiI6MTcyOTU1MjM2MiwicGF0aCI6Ii81MjA4NzM1NS8zNzg1NTY3NDUtZDNmNjYwYTUtN2MxNS00YzAyLWFlMzItNDY2OGJiMmZiMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDIzMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMTIwMWViNDJhMzAzMjIzMzRhYTk5ODQ0ZTk2MTI4NzI4MjBjMDYwMWQ5YmU1Y2RkZmYzNGYyZmQzMzUzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nRl210iBnSUrAe0e3zJ0of_-imioJ9dafY4PqwLnjV8)

Correct, I did this so far in my PR where the all batch jobs link the same folder

> 5. Makes sense to me for interactive jobs
> 6. If admin did not specify `/mnt/efs/shared:/opt`, there is no `/shared` directory currently, but there is `/mnt/efs/shared`, as the EFS is mounted and the dir with the shared packages exist there.

As I have currently written the PR, it seems easier for now to just hard-code the right symlinks.  But in a nutshell: a regular interactive job symlinks the user's personal folder on `/mnt/efs` to `/home/`, and symlinks `/mnt/efs/shared` to `/opt`.  In the "shared admin" mode, `/mnt/efs/shared` is symlinked to `/home/` - this mode only exists to update software in `/mnt/efs/shared`, and would not be used for any interactive sessions doing real data analysis.

> Overall, to help me better understand, I think the two EFSs and their packages should be clearly differentiated. I thought "OEM" mode only referred to the batch/jobman submissions
> 
> I tried consolidating the conversation into an updated image to help us better discuss: ![image](https://private-user-images.githubusercontent.com/52087355/378564162-302277f4-f92c-4f26-9eac-f0253d43b04b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTI2NjIsIm5iZiI6MTcyOTU1MjM2MiwicGF0aCI6Ii81MjA4NzM1NS8zNzg1NjQxNjItMzAyMjc3ZjQtZjkyYy00ZjI2LTllYWMtZjAyNTNkNDNiMDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDIzMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OTYzNjczYTE0YWMyMTIwZjA3MzJlYzQ5N2MyMmI2ZDQ0NDJmYTgyMjgxZmY4NzkzMWRmYjQ0ODlhNzhjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W3pOR2OMtOy4-sonVdv2YPEEZ_dwQqEJN-J50YOdlIo)

When you have a chance feel free to check out my PR, I think implemented everything in the way that currently makes the most sense to me.  We can hopefully iterate from there!

**Comment by danielnachun** [comment]
Also, there does not need to be a `/mnt/efs/admin` - the admin will not have personal packages.  The admin options here are only for managing software in `/mnt/efs/oem` and `/mnt/efs/shared`.

**Comment by Ashley-Tung** [comment]
Great to hear my concerns are already addressed in the PR - thanks for taking the time to read my messages! I'll be taking a look at the PR then

**Comment by danielnachun** [comment]
I'm closing this as completed because it has now been implemented by https://github.com/rfeng2023/mmcloud/pull/121.
