### ISSUE TITLE
Mounting an S3 bucket to a local directory

### ISSUE THREAD

**Issue by Bale4** [rfeng2023/mmcloud#12]
`--mount statfungen/ftp_fgc_xqtl/sos_cache/$username:/home/$username/.sos \`

doesn't create statfungen/ftp_fgc_xqtl/sos_cache/$username folder automatically. I manually  created a folder ($username) on my machine and copied to statfungen/ftp_fgc_xqtl/sos_cache/

 Is there a way to improve this feature?

**Comment by gaow** [comment]
@Bale4 i believe we can do this by improving the `--mount` function. For now please do it manually. After everything works and data production starts under your account, let's talk to @Ashley-Tung to make this improvement

**Comment by Ashley-Tung** [comment]
I submitted a ticket to our engineering team to provide better error messages for this and similar cases. That way, there would be no need to ssh into the Opcenter to find the root cause. However, MMC will not create a directory in your bucket. Nothing will be done to the bucket until it has been mounted.

While this directory check could technically be done within the wrapper script, this will require the user to install the aws cli and set up their bucket keys in their own machine, which may not be worth it, unless there are other ideas?

**Comment by Bale4** [comment]
@Ashley-Tung thanks!
