### ISSUE TITLE
Two quick improvements to make to mm_jobman.sh

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#36]
1. This line https://github.com/rfeng2023/mmcloud/blob/main/src/mm_jobman.sh#L579 does not work ... it is supposed to count how many commands are there in the `commands` variable and check if it is greater than 1. But `${#commands[@]}` does not work. We need to fix it
2. The script now is a bit ugly here:

```bash
...
    printf "%%s\\\\n" ${commands[@]} | parallel -j \$num_parallel_commands ${no_fail_parallel}
else
    printf "%%s\\\\n" ${commands[@]} | while IFS= read -r cmd; do
        eval \$cmd ${no_fail}
    done
fi
```
because we repeat `${commands[@]}` twice which is lots of text when we have hundreds of codes in it. It is hard to read. Can we try to implement it like this:

```bash
commands_to_run=${commands}
...
    printf "%%s\\\\n" \${commands_to_run[@]} | parallel -j \$num_parallel_commands ${no_fail_parallel}
else
    printf "%%s\\\\n" \${commands_to_run[@]} | while IFS= read -r cmd; do
        eval \$cmd ${no_fail}
    done
fi
``` 

so we assign the `commands` text into a local variable `commands_to_run` and use that in the if ... else statements. This will make reviewing the codes much easier -- it shortens the script drastically by half.

**Comment by Ashley-Tung** [comment]
Regarding (1), the issue seems to be that the `commands` variable is holding all commands as one value, due to this line: `commands=$(echo -e "$all_commands" | sed -n "$start,${end}p" | tr '\n' ' ')`.
Echoing the variable, as well as the first element of the variable gives the same value
```
echo $commands
echo "${commands[0]}"
```
This is also due to `all_commands` being a string that contains all of the commands of the job script in one variable.
```
while IFS= read -r line; do
        if [ -z "$line" ]; then
            continue  # Skip empty lines
        fi
        all_commands+="'$line'\n"
        total_commands=$(( total_commands + 1))  
    done < <(sed -e '$a\' $script_file) # always add a newline to the end of file before sending it in
    all_commands=${all_commands%\\n}
```

There are multiple ways to fix this, such as converting `all_commands` or `commands` into an actual array. I can work on these ideas to provide the simplest solution, but let me know what you think @gaow

**Comment by Ashley-Tung** [comment]
The easiest way to count the number of commands in `commands` without much change is creating another `commands_length` variable, since it seems we only look for the length of `commands` once in the script generation
```
commands_length=$(eval "array=($commands); echo \${#array[@]}")
```

**Comment by Ashley-Tung** [comment]
The line in the script generation can then be
```
if [[ \$num_parallel_commands -gt 1 && ${commands_length} -gt 1 ]]; then
```
