### ISSUE TITLE
Improving Jupyter Notebook Setup on Cloud Instances:

### ISSUE THREAD

**Issue by rfeng2023** [rfeng2023/mmcloud#46]
1. A more efficient method to access Jupyter notebooks hosted on cloud instances through the CLI
As the current approach—manually retrieving the public IP, appending :8888 to it, and then copying the access token from a log file—is cumbersome. Ideally, I'm looking for a solution that simplifies or automates this process, making it quicker and more user-friendly. I've developed a script to simplify accessing a Jupyter notebook on a cloud instance by generating a direct URL (public IP:8888:token). The script is available at [Jupyter Setup Script](https://github.com/rfeng2023/mmcloud/blob/main/src/jupyter_setup.sh). However, I believe there's room for improvement with @Ashley-Tung 's help:
- 1.1 Would switching from spot instances to on-demand instances prevent the IP from changing frequently, thus maintaining a stable working status?
- 1.2 Currently, the mount mode is read-only. Attempting to enable read-write mode (mount = 'rw') results in errors. 
- 1.3 Is there a way to automatically monitor the job status and switch the instance to suspend mode (e.g. if inactive >1h ) to save costs?
- 1.4 Are there any additional parameters or configurations that could enhance this setup?
2. Managing IP Changes on Suspended Instances:
Even with the script, resuming a suspended instance leads to a change in the public IP, requiring manual retrieval and login. Is there a simpler method to access Jupyter notebooks on cloud instances without repeatedly navigating through the GUI to obtain IPs and tokens?
3. Optimizing Jupyter Notebook Usage in the Cloud:
- 3.1 Setting up and resuming Jupyter notebooks on the cloud is time-consuming (> 10 mins) and relatively expensive (approximately $20/day). How can this process be optimized?
- 3.2 Should we automate the opening of Jupyter notebooks using the script mentioned (point 1)? If the issue of changing IPs (point 2)upon resumption isn't resolved, is this still beneficial?
- 3.3 What configurations can be applied to minimize costs while using Jupyter in the cloud?
- 3.4 Is it more cost-effective to suspend the Jupyter instance after use or terminate it and set up a new one for each session?
- 3.5 Any other suggestions for efficient and cost-effective use of Jupyter notebooks in the cloud are welcome.
4. Automating Updates for R Package Containers:
Updating R package containers in the vedio from @Ashley-Tung seems promising, but I can image that many users may prefer a more straightforward approach than following a video guide. They might opt to install everything directly in a Jupyter notebook and leave it running indefinitely. However, accidental job cancellations could deter users from restarting the process. Is there a script or application that can automate the update of containers whenever a new package is installed, simplifying the process for users?

**Comment by gaow** [comment]
Thanks @rfeng2023 ! @Ashley-Tung we would like to finalize on some version of this so collaborators can start working on our results directly without egress. Currently the cost ($600 a month!), easy to use and easy to update packages are the 3 major factors that discourages from pursuing this route. 

Just adding one technical point to Ru's list -- we would also want to optionally disable the "float" behavior for interactive analysis. Sometimes people can load too much data to the memory overtime, not realizing that's not necessary. Limited memory helps reminding people to "garbage collect" large data objects that are no longer relevant. 

We have a very good workflow using JupyterLab on HPC. Just like our batch job execution #25 , I would hope that our JupyterLab experience can be optimized to beat that on HPC. That would be the moment people make a comfortable transition into it.

**Comment by gaow** [comment]
For the cost, if we use R5 4 core 32GB without floating, 

```
> 0.29*24*30
[1] 208.8
```

we are looking at a monthly of $208. If we have a suspend feature better supported and automated, we can perhaps manage it at $100? Then we can look into NIH stride which might be further discount (that I can talk to CUMC AWS team after we transfer the account). My aim is $60 per instance per month.

**Comment by Ashley-Tung** [comment]
Hi @rfeng2023 and @gaow , to address your concerns:
```1.1 Would switching from spot instances to on-demand instances prevent the IP from changing frequently, thus maintaining a stable working status?```
No, switching to an on-demand instance does not automatically prevent IP from changing. Even when you suspend an On-Demand instance, it frees up the IP so when you resume an On-demand instance, the IP will be different. This is where the gateway comes it. It makes sure the IP remains connected to your instance. I talk about the cost in part 3.1

```1.2 Currently, the mount mode is read-only. Attempting to enable read-write mode (mount = 'rw') results in errors.```
Are you mounting your statfungen bucket and how are you mounting it? I can test on my side but I would also appreciate it if you show me what error is happening.

```1.3 Is there a way to automatically monitor the job status and switch the instance to suspend mode (e.g. if inactive >1h ) to save costs?```
You can always monitor the job through the GUI or CLI and you can suspend the instance through the GUI/CLI as well. To suspend through the CLI is `float suspend -j <job_id>`. I do not believe we have an option to suspend an instance when there are certain behaviors. 

```1.4 Are there any additional parameters or configurations that could enhance this setup?```
I would recommend adding `--withRoot` at the end of your command so that you are running as a root user. This would make it easier to install packages and access your bucket, but I understand if you do not want to be giving out that privilege.

```2. Even with the script, resuming a suspended instance leads to a change in the public IP, requiring manual retrieval and login. Is there a simpler method to access Jupyter notebooks on cloud instances without repeatedly navigating through the GUI to obtain IPs and tokens?```
If you have a gateway set up, the IP will remain the same even after suspension. You will only need to retrieve the token once at the very start and can set a password then. That way, you do not have to get a token every time.

```3.1 Setting up and resuming Jupyter notebooks on the cloud is time-consuming (> 10 mins) and relatively expensive (approximately $20/day). How can this process be optimized?```
Your jupyter notebook should not be that expensive. You can see in this instance, which is using an On-Demand 4 core 16GB instance (yours can be smaller) ran for 10 days and only cost $40. So about $4 a day.
![image](https://github.com/rfeng2023/mmcloud/assets/52087355/4627f049-fcb1-4e7a-a31e-bc62255121cc)
Additionally, a gateway is just a small on-demand instance as well and you can limit its size. Mine ran for 10 days and only cost around $20, so $2 a day.
![image](https://github.com/rfeng2023/mmcloud/assets/52087355/bbb7afa4-a196-46d9-b362-6e9a295559d4)
In total, if you were to run instances of the same type, you should not see more than $6 a day, and this can be set to a smaller amount. If your instance ends up much more expensive than this, please send a screenshot of the cost of the instance so we may take a look.

```3.2 Should we automate the opening of Jupyter notebooks using the script mentioned (point 1)? If the issue of changing IPs (point 2)upon resumption isn't resolved, is this still beneficial?```
We can definitely automate the generation of jupyter notebooks. The gateway will make sure the IP remains the same, but the script itself should not be affected by the changing IP, because it is meant for initial setup. If we want to add a section on opening a notebook (i.e. connecting to it), that should be done **right after you create the instance**.
It doesn't make sense to connect through the script **after the script is done running**. How will your script know which instance to connect to if it didn't just create it? Perhaps a separate script to look through your currently running jupyter instances and grabbing the IP for them? That's a decision for you to make if we want more scripts.

```3.3 What configurations can be applied to minimize costs while using Jupyter in the cloud?```
Smaller instances, and I would still recommend using Spot Instances. The r5* types have a low chance of being spot reclaimed. You can check out this [link](https://aws.amazon.com/ec2/spot/instance-advisor/) to see what instances are best for you in your region, as some instances have a higher change of reclamation than others. Reclamation should not be an issue for the IP and your work as we can check point and remain on the same IP.

```3.4 Is it more cost-effective to suspend the Jupyter instance after use or terminate it and set up a new one for each session?```
There are two modes we have for suspending an instance. Hot mode will checkpoint your instance but not your volumes. The volumes will continue to incur costs. Cold mode will checkpoint your instance and volumes. Afterwards, the volumes will be removed so that you will not incur costs.
However, re-running a suspended instance is faster in Hot mode than in Cold mode, because Hot mode still have their volumes up. You can do this via the GUI (performance mode is Hot and eco mode is Cold) or CLI with `float suspend -j <job_id> --cold/--hot`
Overall, starting up an already suspended instance would be faster than starting a new one via your script.

```3.5 Any other suggestions for efficient and cost-effective use of Jupyter notebooks in the cloud are welcome.```
Check point 3.1 and point 3.3.

```We would also want to optionally disable the "float" behavior for interactive analysis.```
When the jupyter instance is started up via the script, we can add a parameter `--migratePolicy [disable=true]` so that only that instance will not float anywhere.

**Comment by Ashley-Tung** [comment]
```1.2 I've added mode='rw' as default (actually fixed), we can add more options in scrpit.```
Awesome! I am glad it works. We can then spend time on what options/changes would be best for the script

```3.1 The cost includes setting up the gateway, which is another expense that I am concerned about.```
I am a little confused about what you are trying to say here. From my tests, you should not be charged more than $6 a day with the instance sizes I previously showed (unless you are using overall larger instances). The $6 I am referring to also includes the cost of the gateway per day. $4/day for a On-Demand 4 core 16GB instance for the Jupyter server and $2/day for the On-Demand 2core 4GB instance for the gateway, summing to $6/day.

```3.2```
Apologies, it seems I misinterpreted your initial question. What you propose in your script and screenshots make sense: we can definitely wait for the instance to execute (after we create it through the script) and share the URL as an stdout). We can also open a browser with the url we grab.
My concern was in the scenario where we finish running the script, maybe we exit out of our machine, and we forget what url to open. It would not make sense to run your script again just to open a browser tab to your jupyter server, but this is remedied via the "log file" you suggest!

```Does this mean that once the instance is established, it cannot be modified?```
Yes, once an instance is running, you cannot modify its parameters. This is a core mechanic to MMC. You could always cancel the run immediately and re-submit with updated parameters

**Comment by gaow** [comment]
@Ashley-Tung $6 per day is $4 per day for the instance and $2 for gateway right? I wonder if we can have multiple instances using the same gateway? Say 10 people in my lab each working 12hrs -- if we can suspend then it's $3 per day per person. We will have $2 for gateway for all the 10 instances. That will be $32 per day in my lab, and $900 per month, $10K per year. This may be sustainable if i budget it in my next grant proposal. The key is that can we get away with just runing one gateway for eveyrone? 

> My concern was in the scenario where we finish running the script, maybe we exit out of our machine, and we forget what url to open. It would not make sense to run your script again just to open a browser tab to your jupyter server, but this is remedied via the "log file" you suggest!

@Ashley-Tung do you have a better proposal than what @rfeng2023 currently implemented?

> Yes, once an instance is running, you cannot modify its parameters. This is a core mechanic to MMC. You could always cancel the run immediately and re-submit with updated parameters

The scenarios i worry about is if we allow for automatic migration it migrates to a larger machine which is what we need for eg a few minutes to complete a step in our interactive analysis. Then we don't need that much anymore. We wantto migrate to a smaller machine. Is there a way to trigger that quickly eg via CLI? Or maybe easier, the next time we resume can we always reset to the setup we initially demanded? If so I'm happy.

**Comment by Ashley-Tung** [comment]
1. Gateways can be shared! The $4/day is for an On-Demand 4 core 16GB instance. This can definitely be set to a spot-instance, and a smaller one at that as well. The $4/day is not a set value for jupyterhub instances. The Spot version of this can easily be $2/day. 
Since gateways can be shared, $2 + $2/day will be around $62/month (for a 30-day month)

2. No, the log file is already a good proposal!
3. If we do not want the jupyter instances themselves to not migrate at all, this can be done with `--migratePolicy [disable=true]`. As of now, there is no way to manually trigger a migration to a larger/smaller instance.

**Comment by gaow** [comment]
Reorgnaized into various smaller tickets. Close it for now. Let's discuss in other relevant tickets or use new ticket.
