### ISSUE TITLE
Output file corruption on AWS when disrupted by float

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#58]
We experience from time to time corrupted files when we write output to AWS. Not very often but not rare either. About 1 or 2 out of every 1000 analysis performed. This is very awkward. We need to basically run our analyis twice or more just to pick up a handful of such cases.

@Ashley-Tung this would also be a headache to manage. I think we can have a solution in mm_jobman.sh. In principle, instead of writing the output to aws directly we first write to local and upload it right after a command completes. This is different from --upload which only happens at the very end, so we can still see the results kind of real-time. I need to think how to do this though since we want to be very specific for the files to copy ... I have an idea that I will propose some details to discuss and implement.

**Comment by gaow** [comment]
@Ashley-Tung and Hao: thinking of this, I figure we might be able to do this by 

1. Don't mount output folder
2. Add to the generated command automatically something like this `run_our_command && aws s3 cp ../output/gene_name/ AWS_bucket --recursive` --- Hao this is going to be a command splitter feature not mm_jobman.sh.

**Comment by hsun3163** [comment]
so that is like the old version where we cp the file back to AWS manually?

**Comment by gaow** [comment]
> so that is like the old version where we cp the file back to AWS manually?

yes and no. The difference is that likei said, `This is different from --upload which only happens at the very end, so we can still see the results kind of real-time.`

As @Ashley-Tung pointed out this happens because the VM was disrupted as it outputs to AWS. @Ashley-Tung if we write to the VM instead of AWS directly would it be better? We will still have to copy it over though , and that copy process can be distrupted as well? I guess it might be the best if there is a good fix on your end.  So am going to mark this as a bug.

**Comment by Ashley-Tung** [comment]
Hello, I believe I have figured out the cause to the file corruptions. In summary, all five corrupted files are linked to 5 jobs that failed to complete, but the cause for all five is due to incompatible instance issues. This would stop the job prematurely and likely have the output file corrupted. I will be going through each corrupted file and their corresponding failed job.

# [i3swnd9gsiz4j6ky8rdx6](https://23.22.157.8/#/opcenter/jobs/i3swnd9gsiz4j6ky8rdx6/)
For corrupted file `ROSMAP_mQTL.chr13:98173592-102416508.fsusie_mixture_normal_weights_db.rds`
This job has a NoAvailableHost error. The `job.events` does not give us useful information but looking at its entry in `opcenter.log`, no instance was available for it to use.
```
time="2024-02-21T17:52:52.42" level=warning msg="Failed to create instance" error="InsufficientInstanceCapacity: We currently do not have sufficient r5.2xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get r5.2xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1d, us-east-1f.\n\tstatus code: 500, request id: 990d03cc-82bf-4ef7-921e-ba68759c84f2"
...
time="2024-02-21T17:57:59.264" level=warning msg="Ban instance type as no spot/ondemand instance available now" image=pecotmr_docker-z44a24 instType=r5.2xlarge job=i3swnd9gsiz4j6ky8rdx6 type=r5.2xlarge
time="2024-02-21T17:57:59.264" level=warning msg="Failed to create instance, will retry later" image=pecotmr_docker-z44a24 instType=r5.2xlarge job=i3swnd9gsiz4j6ky8rdx6 retried=2
```
The job was stopped prematurely due to lack of resources for the availability zone. I believe Ru has since confirmed with us that this new East opcenter now searches in all availability zones, so this issue should not come up again, unless all availability zones are used up which is unlikely.

# [ki8az38n07odbkytfm70w](https://23.22.157.8/#/opcenter/jobs/ki8az38n07odbkytfm70w/)
For corrupted file `ROSMAP_mQTL.chr5:146235025-152347590.fsusie_mixture_normal_weights_db.rds`
From `job.events`, we see
```
2024-02-21T11:29:09.687: Job status changed: [Floating -> NoAvailableHost]. Mark job done.
2024-02-21T11:29:09.687: Failed to create new instance because: Unsupported instance type (code: 8149)
```
From `opcenter.log` we see
```
time="2024-02-21T11:29:09.164" level=info msg="Ready to create instance" AMI= instanceType=r7i.2xlarge on-demand=false priceLimit=0 priceLimitPercent=0 publicIP=true zone=us-east-1b
time="2024-02-21T11:29:09.687" level=warning msg="Failed to create instance" error="UnsupportedOperation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.\n\tstatus code: 400, request id: 55801cc3-0633-4a97-8942-49d088642d78"
time="2024-02-21T11:29:09.687" level=error msg="Failed to create cloud instance" error="Unsupported instance type (code: 8149)"
time="2024-02-21T11:29:09.687" level=info msg="Failed to create new instance because: Unsupported instance type (code: 8149)" job=ki8az38n07odbkytfm70w
time="2024-02-21T11:29:09.687" level=info msg="Job completed, ready to reclaim job resource" exitCode=-1 id=7cbfe65b3da7240830aa75f14d218d82a306d42ec771fbc7e2bab1e9b71d0e3c job=ki8az38n07odbkytfm70w status=NoAvailableHost
time="2024-02-21T11:29:09.725" level=warning msg="only deal with single host" job=ki8az38n07odbkytfm70w
```
The error here states that the AWS marketplace does not support the `r7i.2xlarge` instance type for us, meaning AWS has not allowed this for us. However, this job was started on 2/20, and on 2/21, we were just given access to the `r7i*` instance types. It is likely when this job was searching for the instance, it was not yet granted to us, despite it being in our allow list. This issue should not come up again, as mentioned in #45 .

# [3229tiwmw1mdqsd9u8t65](https://23.22.157.8/#/opcenter/jobs/3229tiwmw1mdqsd9u8t65/)
For corrupted file `ROSMAP_mQTL.chr19:4674946-11933535.fsusie_mixture_normal_weights_db.rds`
This job failed to complete. Looking at `job.events`, Host is suddenly not found
```
2024-02-24T00:52:09.973: Created instance i-0f0e98d2399e6908c(r5.4xlarge-Spot) at us-east-1c, waiting for it to initialize
2024-02-24T00:57:39.197: Job failed because Host not found (code: 8001)
2024-02-24T00:57:39.197: Job status changed: [Executing -> FailToComplete]. Mark job done.
```
However, we have seen this error before and this timestamp. This error happened during the Opcenter panic reboot mentioned in #50 . This job was also not run with the latest hotfix, which addresses the panic issue.

# [bazoinuyirrsnjtr7pmr0](https://23.22.157.8/#/opcenter/jobs/bazoinuyirrsnjtr7pmr0) and [z8efcrpeqdecc1rvtdsd3](https://23.22.157.8/#/opcenter/jobs/z8efcrpeqdecc1rvtdsd3/)
These jobs are for the files `ROSMAP_mQTL.chr14:68050881-73566530.fsusie_mixture_normal_weights_db.rds` and `ROSMAP_mQTL.chr20:22602410-29602843.fsusie_mixture_normal_weights_db.rds` respectively. They were run around 2/27, so they should be using the latest hotfix.
Both have the same issue, so I will just be referring to the first job. Looking at `job.events`, we can see that the instance was interrupted, but suddenly said the instance type is not supported (we should be support the r5* family, which is what it is on)
```
2024-02-28T01:28:22.087: Job status changed: [Floating -> Executing]
2024-02-28T19:11:04.684: Got spot interruption notice on i-02257f4cee04b19b7
2024-02-28T19:11:04.685: i-02257f4cee04b19b7 is interrrupted, will recover
...
2024-02-28T19:11:06.219: Job status changed: [Executing -> Floating]
2024-02-28T19:11:06.219: Ready to recover workload of i-02257f4cee04b19b7
2024-02-28T19:12:59.263: workload on 172.31.22.228 are checkpointed at 2024-02-28T19:12:59.258Z on i-02257f4cee04b19b7
...
2024-02-28T19:13:39.446: Ready to create new instance to recover
2024-02-28T19:13:39.957: Job status changed: [Floating -> NoAvailableHost]. Mark job done.
2024-02-28T19:13:39.957: Failed to create new instance because: Unsupported instance type (code: 8149)
```

Looking at `opcenter.log`, it gives us more information. Even though we expect to go back to the same instance type after a spot interruption, it seems there were no more of that r5 type, so we picked out the `r7iz.2xlarge`
```
time="2024-02-28T19:13:35.158" level=warning msg="Failed to wait the instance to be terminated" error="Timed out (code: 1023)" inst=i-02257f4cee04b19b7
time="2024-02-28T19:13:35.292" level=info msg="i-02257f4cee04b19b7 has been terminated" inst=i-02257f4cee04b19b7 job=bazoinuyirrsnjtr7pmr0
...
time="2024-02-28T19:13:39.446" level=info msg="Ready to create new instance to recover" job=bazoinuyirrsnjtr7pmr0
time="2024-02-28T19:13:39.446" level=info msg="Ready to create instance" AMI= instanceType=r7iz.2xlarge on-demand=false priceLimit=0 priceLimitPercent=0 publicIP=true zone=us-east-1a
time="2024-02-28T19:13:39.508" level=info msg="Deleted volume" vol=vol-080d951ca6bd89c86 zone=us-east-1a
time="2024-02-28T19:13:39.51" level=info msg="Ready to delete volume" vol=vol-07a85e9bf65e1eaa4 zone=us-east-1a
time="2024-02-28T19:13:39.711" level=info msg="Deleted volume" vol=vol-07a85e9bf65e1eaa4 zone=us-east-1a
time="2024-02-28T19:13:39.713" level=info msg="Ready to delete volume" vol=vol-001cc3d61adc12c67 zone=us-east-1a
time="2024-02-28T19:13:39.883" level=info msg="Deleted volume" vol=vol-001cc3d61adc12c67 zone=us-east-1a
time="2024-02-28T19:13:39.885" level=warning msg="No quota found for metric, skip" metric=Job-hour
time="2024-02-28T19:13:39.957" level=warning msg="Failed to create instance" error="UnsupportedOperation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.\n\tstatus code: 400, request id: 1f726f86-b7b1-4b9b-aa09-079885392419"
time="2024-02-28T19:13:39.957" level=error msg="Failed to create cloud instance" error="Unsupported instance type (code: 8149)"
time="2024-02-28T19:13:39.957" level=info msg="Failed to create new instance because: Unsupported instance type (code: 8149)" job=bazoinuyirrsnjtr7pmr0
time="2024-02-28T19:13:39.957" level=info msg="Job completed, ready to reclaim job resource" exitCode=-1 id=440e650f0bee64d6a007bbce02f33ab1849e63d1fa439d06f710773b1afb1953 job=bazoinuyirrsnjtr7pmr0 status=NoAvailableHost
time="2024-02-28T19:13:39.959" level=error msg="Failed to replace host" error="Unsupported instance type (code: 8149)" spec=i-02257f4cee04b19b7
```
However, we do not support this instance type, as mentioned in #51. Since this job was run on the 2/27, this was actually before we put the instance type in our deny list. [See this slack message for the timestamp](https://memverge-support.slack.com/archives/C06GTN5RSCF/p1709177326440649?thread_ts=1709125791.694419&cid=C06GTN5RSCF).

# Summary
These five file corruptions were due to their respective jobs failing. The issues were simply minimal availability zones, the instance type was not supported at the time, or due to opcenter panic. Since these jobs are not very recent, their solutions have already been addressed since their run.

Please let me know if there is anything else I can elaborate on.

**Comment by gaow** [comment]
@Ashley-Tung sorry am busy now but this is impressive and reassuring.

**Comment by Ashley-Tung** [comment]
Hi @gaow , bringing this back to our attention. Is the next step to rerun these jobs, now that we know the cause?

**Comment by gaow** [comment]
@Ashley-Tung yes we have made a list of these files. We will rerun at some point after our current batch of sQTL analysis is done.

**Comment by Ashley-Tung** [comment]
Hi @gaow have the corresponding runs been resubmitted?

**Comment by gaow** [comment]
@Ashley-Tung not yet. We are waiting for the current analyssi to finish, collect potenial new corruptions then rerun for all corrupted. 

if we don't see any corruption in the analysis that we submitted to 2.5.2 earlier this week, we will close this ticket.

**Comment by Ashley-Tung** [comment]
Hi @gaow , have there been any updates on the analysis? Do the files look alright?

**Comment by gaow** [comment]
@Ashley-Tung still not. We will not have it until next week. But we can close it since it is just a matter of rerun.
