### ISSUE TITLE
Improvement requests as of April 9, 2024 particularly on JuptyerLab

### ISSUE THREAD

**Issue by gaow** [rfeng2023/mmcloud#68]
## Improvements to jupyter_setup.sh

1. Add a switch to choose between spot instance and on demand; default to on demand
2. Add a switch to specify families simply R or M. Default to M. Under the hood we will use the more complicated patterns to set it for the float command. For example

```
--ec2-types R # just R
--ec2-types M # just M
--ec2-types R M # R or M both
```

## Improvements to mm_jobman.sh

1. Add a switch to choose between spot instance and on demand; default to spot
2. Add a switch to specify families simply R or M. Default to R. Under the hood we will use the more complicated patterns to set it for the float command

## Improvements to JupyterLab experience

1. Setup a gateway to prevent IP changes after resuming from suspend; and document how to do it. Share the gateway between all JupyterLab instances in the same opcenter.
2. Automatic suspend instance for eg to hot mode for > 3h inactivity to hot mode, and >6h in activity to cold mode, to save costs --- this is a must have even for me to convince other labs to start using JupyterLab on MMCloud. Otherwise I cannot imagine JupterLab being a popular idea to sell to people. It's a matter of psychology if you think of it --- i would not blink my eyes for batch computing bill > $10K a month; however I would not be happy to see even $10 extra monthly on JupyterLab
3. Update R package containers: youtube videos are not the way to go. As I repeated many times, we don't like youtube tutorials. Everything must be streamlined. On this front, we got very good support from Dan Nachun. The experience will be very much improved and I think this is something memverge should definitely adopt and develop upon. I'll follow up with Dan to formalize this and make it easily accessible by adding documentations
4. In the future, make the step of finding the URL for JupterLab even easier. Such as some links to click on the opcenter interface. 
5. In the future, study the difference between JupyterLab and JupyterHub and provide option for JupyterHab which allows many people from the same group to use one large instance in a shared way but also operate individually in their ow Jupyter environment --- this is not an urgent matter at all; just documenting this possibility in case we are missing out on good features that JupterHub can provide

## Improvements to opcenter

1. Upgrade to version 2.5.3 @rfeng2023
2. Upgrade to the gp3 volume @rfeng2023
3. Allow for both R and M families in opcenters
4. Allow for both spot and on demand instances in opcenters

For 3 and 4 we can add to this ticket: https://github.com/rfeng2023/mmcloud/issues/40 for another reply on "Updated Configurations"

**Comment by Ashley-Tung** [comment]
Hi @gaow , in regards to these points, most of these can be implemented immediately. Namely:
- Improvements to jupyter_setup.sh
- Improvements to mm_jobman.sh
- Opcenter upgrades
- gp3 upgrades
- R and M allow list
- Spot and ondemand allowance (In regards to this, I recall all opcenters had been set to spotOnly for costs savings. As long as you are aware of cost of allowing ondemand instances, this is an easy update)

In regards to `Improvements to JupyterLab experience`:
1. Gateway can be set up automatically and can simply remain, since it is an On-demand instance and will not be removed by AWS. We can make it so the jupyterlab scripts always connect to this same gateway
2. Automatic suspension will require a feature request submission on our part, as this is not implemented anywhere. I can see the benefit of having this feature
3. Sounds good, I will also wait for Daniel's response
4. In regards to finding the JupyterLab URLs, there are already multiple ways to do this without having to search through multiple pages of jobs. Please let me know if these options are still not to your preference. Not many of our users/clients use Jupyter so not much development has gone into its ease of use:
    - You can use the search bar to find the jupyter instance (can search by name)
    - On the gateway tab, you can see all the instances connected to that very gateway (which would include the corresponding jupyter instances)


Please let me know what you think!

**Comment by gaow** [comment]
Thanks @Ashley-Tung . How about we start implementing what you identified as easier updates? 

> (In regards to this, I recall all opcenters had been set to spotOnly for costs savings. As long as you are aware of cost of allowing ondemand instances, this is an easy update)

This is still a concern about cost but I don't think it will be an issue if we default `mm_jobman.sh` to spot only, right? That's why updating `mm_jobman.sh` to allow for that option is important, before we change the settings here. I suggest we add `--allow-on-demand` to `mm_jobman.sh` as optional parameter?

**Comment by Ashley-Tung** [comment]
That can work, and we can do it with the `jupyter_setup.sh` script as well

**Comment by Ashley-Tung** [comment]
All three opcenters now have `SpotFirst` as their VM Policy (will prefer spot instances, but now spot and ondemand instances are available to use
All three opcenters now have `m*` instances on their allow list
I have also updated the configuration commands in #40

**Comment by gaow** [comment]
Splitted this into various smaller issues.
